[package]
name = "rs-cockpit-session"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
env_logger = "0.7"
json = "0.12"
libc = "0.2"
log = "0.4"
